package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceDo;
import org.springframework.stereotype.Component;

@Component
public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Dec 03 18:54:50 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Dec 03 18:54:50 CST 2019
     */
    int insert(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Dec 03 18:54:50 CST 2019
     */
    int insertSelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Dec 03 18:54:50 CST 2019
     */
    SequenceDo selectByPrimaryKey(String name);

    SequenceDo selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Dec 03 18:54:50 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Dec 03 18:54:50 CST 2019
     */
    int updateByPrimaryKey(SequenceDo record);
}